version: '3.12'

services:
  db:
    container_name: 'postgres'
    image: 'postgres:14'
    restart: always
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'