"""empty message

Revision ID: 0125508dd4fb
Revises: 
Create Date: 2025-02-03 18:49:38.508068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0125508dd4fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ownership_form', sa.TEXT(), nullable=False),
    sa.Column('economic_activity', sa.TEXT(), nullable=False),
    sa.Column('number', sa.TEXT(), nullable=False),
    sa.Column('organization', sa.TEXT(), nullable=False),
    sa.Column('inn', sa.TEXT(), nullable=False),
    sa.Column('kpp', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('region', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('employee_count', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_item_inn'), 'common_item', ['inn'], unique=False)
    op.create_index(op.f('ix_common_item_kpp'), 'common_item', ['kpp'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_index(op.f('ix_common_item_kpp'), table_name='common_item')
    op.drop_index(op.f('ix_common_item_inn'), table_name='common_item')
    op.drop_table('common_item')
    # ### end Alembic commands ###
