"""add phone, email, employee_count

Revision ID: 9634067a4108
Revises: a418c60ad058
Create Date: 2025-01-20 17:54:53.688437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9634067a4108'
down_revision: Union[str, None] = 'a418c60ad058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_item', sa.Column('phone', sa.TEXT(), nullable=True))
    op.add_column('common_item', sa.Column('email', sa.TEXT(), nullable=True))
    op.add_column('common_item', sa.Column('employee_count', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_item', 'employee_count')
    op.drop_column('common_item', 'email')
    op.drop_column('common_item', 'phone')
    # ### end Alembic commands ###
